/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillLibrariesRouteRouteImport } from './routes/skill-libraries/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillLibrariesIndexRouteImport } from './routes/skill-libraries/index'
import { Route as SkillLibrariesSkillLibraryIdRouteImport } from './routes/skill-libraries/$skillLibraryId'

const SkillLibrariesRouteRoute = SkillLibrariesRouteRouteImport.update({
  id: '/skill-libraries',
  path: '/skill-libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillLibrariesIndexRoute = SkillLibrariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillLibrariesRouteRoute,
} as any)
const SkillLibrariesSkillLibraryIdRoute =
  SkillLibrariesSkillLibraryIdRouteImport.update({
    id: '/$skillLibraryId',
    path: '/$skillLibraryId',
    getParentRoute: () => SkillLibrariesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skill-libraries': typeof SkillLibrariesRouteRouteWithChildren
  '/skill-libraries/$skillLibraryId': typeof SkillLibrariesSkillLibraryIdRoute
  '/skill-libraries/': typeof SkillLibrariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skill-libraries/$skillLibraryId': typeof SkillLibrariesSkillLibraryIdRoute
  '/skill-libraries': typeof SkillLibrariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skill-libraries': typeof SkillLibrariesRouteRouteWithChildren
  '/skill-libraries/$skillLibraryId': typeof SkillLibrariesSkillLibraryIdRoute
  '/skill-libraries/': typeof SkillLibrariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skill-libraries'
    | '/skill-libraries/$skillLibraryId'
    | '/skill-libraries/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skill-libraries/$skillLibraryId' | '/skill-libraries'
  id:
    | '__root__'
    | '/'
    | '/skill-libraries'
    | '/skill-libraries/$skillLibraryId'
    | '/skill-libraries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillLibrariesRouteRoute: typeof SkillLibrariesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill-libraries': {
      id: '/skill-libraries'
      path: '/skill-libraries'
      fullPath: '/skill-libraries'
      preLoaderRoute: typeof SkillLibrariesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-libraries/': {
      id: '/skill-libraries/'
      path: '/'
      fullPath: '/skill-libraries/'
      preLoaderRoute: typeof SkillLibrariesIndexRouteImport
      parentRoute: typeof SkillLibrariesRouteRoute
    }
    '/skill-libraries/$skillLibraryId': {
      id: '/skill-libraries/$skillLibraryId'
      path: '/$skillLibraryId'
      fullPath: '/skill-libraries/$skillLibraryId'
      preLoaderRoute: typeof SkillLibrariesSkillLibraryIdRouteImport
      parentRoute: typeof SkillLibrariesRouteRoute
    }
  }
}

interface SkillLibrariesRouteRouteChildren {
  SkillLibrariesSkillLibraryIdRoute: typeof SkillLibrariesSkillLibraryIdRoute
  SkillLibrariesIndexRoute: typeof SkillLibrariesIndexRoute
}

const SkillLibrariesRouteRouteChildren: SkillLibrariesRouteRouteChildren = {
  SkillLibrariesSkillLibraryIdRoute: SkillLibrariesSkillLibraryIdRoute,
  SkillLibrariesIndexRoute: SkillLibrariesIndexRoute,
}

const SkillLibrariesRouteRouteWithChildren =
  SkillLibrariesRouteRoute._addFileChildren(SkillLibrariesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillLibrariesRouteRoute: SkillLibrariesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
