/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillLibrariesRouteRouteImport } from './routes/skill-libraries/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillLibrariesIndexRouteImport } from './routes/skill-libraries/index'
import { Route as SkillLibrariesSkillLibraryIdRouteImport } from './routes/skill-libraries/$skillLibraryId'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github/callback'
import { Route as ApiGithubAuthorizeRouteImport } from './routes/api/github/authorize'

const SkillLibrariesRouteRoute = SkillLibrariesRouteRouteImport.update({
  id: '/skill-libraries',
  path: '/skill-libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillLibrariesIndexRoute = SkillLibrariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillLibrariesRouteRoute,
} as any)
const SkillLibrariesSkillLibraryIdRoute =
  SkillLibrariesSkillLibraryIdRouteImport.update({
    id: '/$skillLibraryId',
    path: '/$skillLibraryId',
    getParentRoute: () => SkillLibrariesRouteRoute,
  } as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAuthorizeRoute = ApiGithubAuthorizeRouteImport.update({
  id: '/api/github/authorize',
  path: '/api/github/authorize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skill-libraries': typeof SkillLibrariesRouteRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/skill-libraries/$skillLibraryId': typeof SkillLibrariesSkillLibraryIdRoute
  '/skill-libraries/': typeof SkillLibrariesIndexRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/skill-libraries/$skillLibraryId': typeof SkillLibrariesSkillLibraryIdRoute
  '/skill-libraries': typeof SkillLibrariesIndexRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skill-libraries': typeof SkillLibrariesRouteRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/skill-libraries/$skillLibraryId': typeof SkillLibrariesSkillLibraryIdRoute
  '/skill-libraries/': typeof SkillLibrariesIndexRoute
  '/api/github/authorize': typeof ApiGithubAuthorizeRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skill-libraries'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/skill-libraries/$skillLibraryId'
    | '/skill-libraries/'
    | '/api/github/authorize'
    | '/api/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/skill-libraries/$skillLibraryId'
    | '/skill-libraries'
    | '/api/github/authorize'
    | '/api/github/callback'
  id:
    | '__root__'
    | '/'
    | '/skill-libraries'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/skill-libraries/$skillLibraryId'
    | '/skill-libraries/'
    | '/api/github/authorize'
    | '/api/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillLibrariesRouteRoute: typeof SkillLibrariesRouteRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiGithubAuthorizeRoute: typeof ApiGithubAuthorizeRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill-libraries': {
      id: '/skill-libraries'
      path: '/skill-libraries'
      fullPath: '/skill-libraries'
      preLoaderRoute: typeof SkillLibrariesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-libraries/': {
      id: '/skill-libraries/'
      path: '/'
      fullPath: '/skill-libraries/'
      preLoaderRoute: typeof SkillLibrariesIndexRouteImport
      parentRoute: typeof SkillLibrariesRouteRoute
    }
    '/skill-libraries/$skillLibraryId': {
      id: '/skill-libraries/$skillLibraryId'
      path: '/$skillLibraryId'
      fullPath: '/skill-libraries/$skillLibraryId'
      preLoaderRoute: typeof SkillLibrariesSkillLibraryIdRouteImport
      parentRoute: typeof SkillLibrariesRouteRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/authorize': {
      id: '/api/github/authorize'
      path: '/api/github/authorize'
      fullPath: '/api/github/authorize'
      preLoaderRoute: typeof ApiGithubAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SkillLibrariesRouteRouteChildren {
  SkillLibrariesSkillLibraryIdRoute: typeof SkillLibrariesSkillLibraryIdRoute
  SkillLibrariesIndexRoute: typeof SkillLibrariesIndexRoute
}

const SkillLibrariesRouteRouteChildren: SkillLibrariesRouteRouteChildren = {
  SkillLibrariesSkillLibraryIdRoute: SkillLibrariesSkillLibraryIdRoute,
  SkillLibrariesIndexRoute: SkillLibrariesIndexRoute,
}

const SkillLibrariesRouteRouteWithChildren =
  SkillLibrariesRouteRoute._addFileChildren(SkillLibrariesRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillLibrariesRouteRoute: SkillLibrariesRouteRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiGithubAuthorizeRoute: ApiGithubAuthorizeRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
